### PR TITLE
change command line mode color to purple

### PR DESCRIPTION
**Pull request by cdddg**
I think it would be better if the color of command line mode is purple, so I changed the color of this mode to the purple color of iceberg.vim

### CODE REVIEW

**Comment by gkeep** [comment]
Not familiar with command line mode... Could you show screenshots?

**Comment by cdddg** [comment]
origin style, use [command line mode](https://learnbyexample.gitbooks.io/vim-reference/content/Command_Line_mode.html) (:, /, ..) 
origin_whiteorigin_black

updated style, vimrc set `au CmdlineEnter * redraws`  and use [command line mode](https://learnbyexample.gitbooks.io/vim-reference/content/Command_Line_mode.html) (:, /, ..) 
updated_whiteupdated_black


I think this color is great and can increase the readability of my code when writing it. Hope it can be combined.

**Comment by gkeep** [comment]
Oh, I was just not familiar with vim-airline. 

This looks nice, but as far as I can tell, it will not be merged. Iceberg is more focused on readability and lack of distractions, rather than colorfulness.

You can keep it as a fork of `iceberg.vim` or a setting in your `.vimrc`.

**Comment by cdddg** [comment]
> 哦，我只是對vim-airline不熟悉。
> 
> 這看起來不錯，但是據我所知，它不會被合併。Iceberg更著重於可讀性和分散注意力，而不是豐富多彩。
> 
> 您可以將其保留為的分支`iceberg.vim`或設置`.vimrc`。

no problem

**Pull request closed without merging**
