### PR TITLE
Add link to iterm theme port

### PR DESCRIPTION
**Pull request by epszaw**

### CODE REVIEW

**Comment by gkeep** [comment]
Looks good! 

Could you also add the dark theme to your repository, too? 
I know terminal.sexy provides it via `.xresources`, but it would be nice to have it in a dedicated repository, too.

**Comment by lamartire** [comment]
I think yes. Will made port today 👍

**Comment by lamartire** [comment]
@gkeep done

**Comment by lamartire** [comment]
@cocopon what do you think about the merge? 🙂

**Comment by cocopon** [comment]
Thank you for your contribution, and sorry for my late reply...

- Could you fix the app name in readme from `iterm2` to `iTerm2`?
- Could you re-check a color for `Links` and `Cursor` of the light theme? It is not a color in the palette.
  image

**Comment by lamartire** [comment]
Yes, I will check it on this week.

**Comment by lamartire** [comment]
@cocopon it's done for cursor color in the light theme and readme fix is also pushed.
But I not fully understood you about links colors. I checked blue and magenta colors (commonly links are highlighted with these colors) and they're right. Can you explain?

**Comment by cocopon** [comment]
Screenshot of `Links`:
(`005bbb` is not a part of Iceberg palette)
image

and it will be applied to URL-like text when command key is pressed:
image

**Comment by lamartire** [comment]
Finally, I got it!
Done, @cocopon !

**Comment by cocopon** [comment]
Thank you! Could you re-check a color for `Curosor`? It seems to be back to the previous value.
image

**Comment by lamartire** [comment]
@cocopon done. Again :)

**Comment by cocopon** [comment]
`Links` seems to be back to the previous value again...
https://github.com/lamartire/iceberg-iterm/commit/bc40281501f90cecafb079e37396d51d7ae9a20d#diff-a35d9d7d08ac24d890c8b56d8b3e815ceb9c00c940edd384d435a23e732fb143R308-R315

image

**Comment by lamartire** [comment]
@cocopon again :D

**Comment by lamartire** [comment]
@cocopon any new here?

**Comment by cocopon** [comment]
It seems to be fixed.

BTW, what is `Bold`? I noticed that this is also not a color of the palette.
bold

**Comment by lamartire** [comment]
> It seems to be fixed.
> 
> BTW, what is `Bold`? I noticed that this is also not a color of the palette.
> bold

Which color will fit better here? What do you think?
I propose to use `#33374c` (foreground) or `#8389a3` (white bright).

**Comment by cocopon** [comment]
Do you know how to check a bold text? I'd like to check it on the actual terminal but haven't found a way to print it yet.

**Comment by lamartire** [comment]
That it. 

Source code here (you need to install chalk):
```js
const chalk = require('chalk')

console.log(chalk.bold('Bold text here!'))
```

image

**Comment by cocopon** [comment]
Thank you for sharing the code! I understand. `white bright` seems better for this case.

**Comment by lamartire** [comment]
@cocopon done for the both themes! <3

**Comment by cocopon** [comment]
- Dark Foreground should be `#c6c8d1`
- Light Bold should be `#262a3f`
- Light Links seems to be back to the previous value again...

**Comment by lamartire** [comment]
I'm sorry, but iterm2 has some problems with themes exporting. Check it please again.

**Comment by cocopon** [comment]
Found additional issues:
- Dark `Cursor` should be same as `Foreground` (`#c6c8d1`)
- Dark `Cursor text` should be same as `Background` (`#161821`)
- Dark `Selected text` should be same as `Foreground` (`#c6c8d1`)
- Light `Cursor text` should be same as `Background` (`#e8e9ec`)
- Light `Selection` should be same as `Visual` of Vim (`#c9cdd7`)
- `Cursor guide` should be same as `Cursorline` of Vim
  - Dark: `#1e2132`
  - Light: `#dcdfe7`

**Comment by lamartire** [comment]
@cocopon done

**Comment by lamartire** [comment]
@cocopon done here

**Comment by cocopon** [comment]
- These values are rolled back... Please, please re-check colors before/after commit:
  - Dark `Foreground`
  - Dark `Bold`
  - Light `Bold`
  - Light `Links`
- Should `Cursor guide` have alpha? I think opaque color is better

**Comment by cocopon** [comment]
Feel free to reopen the issue if you have any updates.

**Comment by lamartire** [comment]
@cocopon yeah, when I'll done it – I write you and reopen the issue

**Comment by lamartire** [comment]
@cocopon seems like I fix here everything. I hope, that's really everything now.

**Comment by lamartire** [comment]
So, I can't reopen this PR. Should I create new one?

**Comment by lamartire** [comment]
@cocopon can you review the last changes?

**Comment by cocopon** [comment]
Related: https://github.com/cocopon/iceberg.vim/pull/105#issuecomment-2131374689

**Pull request closed without merging**
