### PR TITLE
light theme for airline and lightline

### PR DESCRIPTION
**Pull request by gkeep**
I see that you've started working on a light theme around 1.5 years ago, but never continued after creating the base vim colorscheme. I really want to see the light theme released, so here I am, doing what I can.

So far, I've added light colorscheme to airline and lightline.

It's would be perfectly usable right now, if not for the contrast between background color and cursor.
qwe
<div align="center"><em>Dark and light themes side by side, for comparison</em></div>

### CODE REVIEW

**Comment by gkeep** [comment]
Not sure why, but the issue above applies to terminal only. Everything looks fine in GUIs (tested in gvim and [neovide](https://github.com/Kethku/neovide)). 

Completely lost on this one, so any help would be appreciated!

**Comment by cocopon** [comment]
Thank you for the contribution!

As you said development of light theme is pending for 1.5 years, but now is a good time to restart because...

- I need one (dark theme is hard to see in a bright room...)
- You also need one :)
- The number of GitHub stars will soon reach 1,000 🌟

airline and lightline theme will be compiled from `src/template-airline.vim` and `src/template-lightline.vim` so we also need to modify them. I'll review your changes and apply it for them later.

Please refer #62 to see the development status.

**Comment by gkeep** [comment]
Fixed merge conflicts, ready to merge now! 👍

**Comment by cocopon** [comment]
Thank you for resolving conflicts! Finally, could you squash multiple commits into a single commit and force-push it? This makes your changes simple and clear.

**Comment by gkeep** [comment]
Whoops, forgot some whitespace... Sorry for the force-push spam!

**Comment by cocopon** [comment]
Merged. Big thanks to your contribution!!

**Pull request merged**
