### PR TITLE
iceberg theme for terminator

### PR DESCRIPTION
**Pull request by snowiow**
Hi, I really like your colortheme and I want to have this theme in the rest of my environment as well. That's why I made a theme for the terminator terminal emulator.

Greetings

### CODE REVIEW

**Comment by cocopon** [comment]
Thank you for loving the color scheme!
I tried to run Terminator in my environment but it doesn't work (raises SystemError)... so I cannot see your work.

I found a color `#d1a8ad` (dimmed red) in your palette, but it doesn't seem to be in Iceberg. Would it be possible to replace it with Iceberg one? (e.g. purple `#a093c7`)

**Comment by cocopon** [comment]
Found more colors:
- `#adc1cb` (dimmed sky blue)
- `#673e43` (dark red?)

**Comment by snowiow** [comment]
Yes, I have taken the colors from the [Xresources version](https://gist.github.com/97-109-107/063193d150df272a049b) but I can change it accordingly. With what should #adc1cb  and #673e43 be replaced? Thanks in advance

**Comment by cocopon** [comment]
Oh I didn't check the Xresources version carefully...
Would you share screenshots that contain those colors?

**Comment by cocopon** [comment]
Please reopen the PR if you have progress.

**Pull request closed without merging**
