### PR TITLE
fix: treesitter highlights

### PR DESCRIPTION
**Pull request by arrow2nd**
Thanks for the great color theme!

Fixed broken highlighting in some file types due to the discontinuation of the `TS*` highlight group in the latest treesitter.

> https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1279974776

This is my first time editing a color theme, so I would appreciate it if you could let me know if there are any flaws.

### Before

before

### After

after

### CODE REVIEW

**Comment by gzbd** [comment]
Nice job. Since [this commit](https://github.com/nvim-treesitter/nvim-treesitter/commit/42ab95d5e11f247c6f0c8f5181b02e816caa4a4f) in nvim-treesitter repo, old `TS*` highlight groups don't work anymore. Any chance merging this into master? I'm using @arrow2nd and LGTM

**Comment by cocopon** [comment]
Thank you for your contribution!

Is it okay to delete old declarations? I'm worried about the impact on people using the old environment.

**Comment by arrow2nd** [comment]
Indeed, some people may be using the old version.

If so, would it be better to keep the old declaration and modify it to add the new one?

**Comment by arrow2nd** [comment]
The removal of old declarations in treesitter has been undone.

Also, I noticed that the highlighting of comment tags (such as `NOTE:`) was broken, so I fixed it.

### Before

image

### After

image

**Comment by cocopon** [comment]
Merged, thanks!

**Comment by cocopon** [comment]
Some error occurred after merging this PR: #108

It seems that Vim doesn't support the name format like `@foobar`... do you know anything about this?

**Comment by arrow2nd** [comment]
It seems to be a Neovim-only specification that "@" can be used in group names.

> https://neovim.io/doc/user/syntax.html
> 
> The name for a highlight or syntax group must consist of ASCII letters,
digits, underscores, periods and @ characters.  As a regexp it is
[a-zA-Z0-9_.@]*.

I am not very familiar with Vim/Neovim yet, so I overlooked it. Sorry.

**Comment by cocopon** [comment]
Thank you for investigating. Provisionally I've reverted this change. #109

**Pull request merged**
